### ISSUE TITLE
cmaq can't read the output

### ISSUE THREAD

**Issue by clearsky112** [barronh/aqmbc#3]
Hello,

   I used aqmbc to generate BCON files from Geos-Chem to CMAQ 5.3.2, but the CMAQ model doesn't work and the error was shown as below. I'm new to the CMAQ model and wonder whether you could help me solve the problem?

Thanks in advance!

 >>--->> WARNING in subroutine READ3
     Requested variable "
OXYL.units = "p" not available
     M3WARN:  DTBUF 8:00:00   June 24, 2018 (2018175:080000)

     *** ERROR ABORT in subroutine retrieve_boundar on PE 000
     Could not read BNDY_CONC_1                              file
 PM3EXIT:  DTBUF 8:00:00   June 24, 2018
     Date and time 8:00:00   June 24, 2018  (2018175:080000)

**Comment by barronh** [comment]
Post the output of ‘ncdump -h /path/to/your/file’

**Comment by clearsky112** [comment]
> Post the output of ‘ncdump -h /path/to/your/file’
[out.log](https://github.com/barronh/aqmbc/files/8179822/out.log)

**Comment by barronh** [comment]
Sorry, one more thing. What does `ncdump -k` say? Are your files NETCDF4_CLASSIC or NETCDF3_CLASSIC? If NETCDF4_CLASSIC, was your ioapi build with netcdf4 support?

**Comment by barronh** [comment]
One quick thing to try, use m3xtract to copy the file. Then, see if the copy works. This type of problem is often a metadata problem that can be hard to track down.

**Comment by clearsky112** [comment]
> One quick thing to try, use m3xtract to copy the file. Then, see if the copy works. This type of problem is often a metadata problem that can be hard to track down.

Thank you so much! It's really helpful. I used m3xtract to find the issue that was related to the global attributes, I changed the filedesc and then it worked.

**Comment by barronh** [comment]
Great work finding it!
