### ISSUE TITLE
Boundary conditions layers problem

### ISSUE THREAD

**Issue by haohe1982** [barronh/aqmbc#5]
I have run the aqmbc software to process the GEOS-Chem outputs for CMAQ. In the .cfg file I have the following setting:

vgtop=5000
vglvls=[
    1.0, 0.9975, 0.995, 0.99, 0.985, 0.98, 0.97, 0.96, 0.95, 0.94,
    0.93, 0.92, 0.91, 0.9, 0.88, 0.86, 0.84, 0.82, 0.8, 0.77,
    0.74, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3,
    0.25, 0.2, 0.15, 0.1, 0.05, 0.0
    ]

The generated outputs have 47 layers (I select 47L GEOS_Chem and please see below) instead of 35 for my CMAQ.  What should I do to change that?

netcdf GEOSChem.SpeciesBC.20160101_0000z.12US2.BCON.nc {
dimensions:
        PERIM = 1288 ;
        TSTEP = UNLIMITED ; // (240 currently)
        LAY = 47 ;
        VAR = 1 ;
        DATE-TIME = 2 ;

**Comment by barronh** [comment]
I think this is a version pseudonetcdf issue. See issue pseudonetcdf issues https://github.com/barronh/pseudonetcdf/issues/90 and pseudonetcdf pull request https://github.com/barronh/pseudonetcdf/pull/93. This should be addressed if you have the a recent version. Can you reply with your version number?:

```
python -ic "import PseudoNetCDF as pnc; print(pnc.__version__)"
```

**Comment by haohe1982** [comment]
Your python command doesn't work (see below), but I used 'pip list' and checked my version of pseudonetcdf as 3.1.0. I installed the aqmbc software very recently, so the PNC should be up to latest.

 Btw, the GEOS-Chem I am working is the CH4 version not a normal full chemistry run, i.e., only CH4 in the CONC file. Could it cause the error? 

python -ic "import PseudoNetCDF as pnc; print(pnc.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'PseudoNetCDF' has no attribute '__version__'

**Comment by barronh** [comment]
The rendering is wrong if you aren’t logged in. The version should have two underscores before and after it.

**Comment by haohe1982** [comment]
sorry strange when I post my command as the comment the two '_' disappear. Please see the screenshot attached.

![New Microsoft PowerPoint Presentation](https://user-images.githubusercontent.com/55818058/206082458-3c221bca-9d56-4f6c-b297-2367ac13280c.png)

**Comment by barronh** [comment]
Please update your PseudoNetCDF. The latest version is 3.2.2. If that doesn't resolve the issue, I'll dig further. The newer versions have the __version__ attribute.

**Comment by haohe1982** [comment]
It solved the problem. Thanks a lot and you can close this ticket.
